# ==== build_scan_soil_moisture_latest.R =====================================
#
# PURPOSE:
#   Fetch recent/latest USDA NRCS SCAN soil-moisture observations and write a
#   small static GeoJSON feed for the BRIM Ops Live SCAN layer.
#
# OUTPUTS:
#   docs/data/scan_soil_moisture_latest.geojson
#   docs/data/scan_soil_moisture_latest_summary.json
#
# DESIGN:
#   - The station index is exported from the main BRIM project and committed to
#     the live-data feed repo.
#   - Latest/recent soil moisture values are fetched with soilDB::fetchSCAN().
#   - Soil depths are displayed in inches for the BRIM audience.
#   - The feed preserves all available latest depths per station and selects one
#     display depth for map symbology and compact hover text.
#   - Historical percentiles/ribbon plots are intentionally not built here.
#     Those will be generated by a later local preprocessing step and joined
#     into this feed once the compact historical context files exist.
#
# HOW TO RUN LOCALLY FROM THE FEED REPOSITORY:
#   Rscript scripts/build_scan_soil_moisture_latest.R
#
# REQUIRED INPUT:
#   data/input/scan_station_index.csv
#
# NOTES:
#   SCAN observations are suitable for screening and situational awareness.
#   Values are provisional and may be delayed, revised, or unavailable when a
#   station/sensor is offline. BRIM should display observation age/staleness.
# ============================================================================

# ---- 1. Packages ------------------------------------------------------------

required_pkgs <- c(
  "soilDB", "dplyr", "readr", "lubridate", "jsonlite", "tibble", "purrr", "stringr", "tidyr"
)

missing_pkgs <- required_pkgs[!vapply(required_pkgs, requireNamespace, logical(1), quietly = TRUE)]

if (length(missing_pkgs) > 0) {
  stop(
    "Missing required R packages: ", paste(missing_pkgs, collapse = ", "),
    "\nInstall them before running locally, or let the GitHub Action install them."
  )
}

## Suppress package progress UI; this feed prints its own compact progress.
options(
  cli.progress_show_after = Inf,
  cli.progress_handlers = "none"
)

suppressPackageStartupMessages({
  library(soilDB)
  library(dplyr)
  library(readr)
  library(lubridate)
  library(jsonlite)
  library(tibble)
  library(purrr)
  library(stringr)
  library(tidyr)
})

# ---- 2. Paths, constants, and switches -------------------------------------

station_index_csv <- Sys.getenv(
  "SCAN_STATION_INDEX_CSV",
  unset = "data/input/scan_station_index.csv"
)

out_geojson <- Sys.getenv(
  "SCAN_SMS_GEOJSON",
  unset = "docs/data/scan_soil_moisture_latest.geojson"
)

out_summary <- Sys.getenv(
  "SCAN_SMS_SUMMARY_JSON",
  unset = "docs/data/scan_soil_moisture_latest_summary.json"
)

lookback_days <- suppressWarnings(as.integer(Sys.getenv(
  "SCAN_SMS_LOOKBACK_DAYS",
  unset = "30"
)))
if (is.na(lookback_days) || lookback_days < 3) lookback_days <- 30L

## Default depth for map display / hover if available.
## Keep all depths in the feature properties; this order only chooses the
## compact display value. Historical/popup plotting can revisit this later.
display_depth_preference_in <- suppressWarnings(as.integer(strsplit(Sys.getenv(
  "SCAN_SMS_DISPLAY_DEPTH_PREFERENCE_IN",
  unset = "8,20,4,2,40"
), ",", fixed = TRUE)[[1]]))
display_depth_preference_in <- display_depth_preference_in[!is.na(display_depth_preference_in)]
if (length(display_depth_preference_in) == 0) display_depth_preference_in <- c(8L, 20L, 4L, 2L, 40L)

standard_depth_order_in <- c(2L, 4L, 8L, 20L, 40L)
request_pause_sec <- suppressWarnings(as.numeric(Sys.getenv(
  "SCAN_SMS_REQUEST_PAUSE_SEC",
  unset = "0.15"
)))
if (is.na(request_pause_sec) || request_pause_sec < 0) request_pause_sec <- 0.15

feed_build_time_utc <- format(lubridate::with_tz(Sys.time(), "UTC"), "%Y-%m-%dT%H:%M:%SZ")
feed_build_date_utc <- as.Date(lubridate::with_tz(Sys.time(), "UTC"))
lookback_start_date <- feed_build_date_utc - lookback_days
fetch_years <- sort(unique(lubridate::year(seq(lookback_start_date, feed_build_date_utc, by = "day"))))

# ---- 3. Small helpers -------------------------------------------------------

pt_chr <- function(x) {
  x <- as.character(x)
  x <- trimws(x)
  x[x == "" | is.na(x) | toupper(x) %in% c("NA", "NULL", "NAN")] <- NA_character_
  x
}

pt_num <- function(x) {
  suppressWarnings(as.numeric(gsub(",", "", as.character(x))))
}

pt_fmt_num <- function(x, digits = 1, suffix = "") {
  x <- suppressWarnings(as.numeric(x))
  out <- rep(NA_character_, length(x))
  ok <- !is.na(x)
  out[ok] <- paste0(formatC(x[ok], format = "f", digits = digits, big.mark = ","), suffix)
  out <- sub("(\\.\\d*?)0+([^0-9]|$)", "\\1\\2", out)
  out <- sub("\\.([^0-9]|$)", "\\1", out)
  out
}

pt_depth_in_from_sensor <- function(sensor_id, depth_cm) {
  sensor_id <- as.character(sensor_id)
  from_sensor <- suppressWarnings(as.integer(stringr::str_match(sensor_id, "I_([0-9]+)")[, 2]))
  from_cm <- suppressWarnings(as.integer(round(as.numeric(depth_cm) / 2.54)))
  out <- ifelse(!is.na(from_sensor), from_sensor, from_cm)
  out <- as.integer(out)
  out
}

pt_stale_class <- function(age_days) {
  dplyr::case_when(
    is.na(age_days)   ~ "missing",
    age_days <= 2     ~ "fresh",
    age_days <= 7     ~ "watch",
    age_days <= 30    ~ "stale",
    TRUE              ~ "very stale"
  )
}

pt_stale_label <- function(age_days) {
  dplyr::case_when(
    is.na(age_days)   ~ "No recent observation",
    age_days <= 2     ~ "Fresh",
    age_days <= 7     ~ "Watch",
    age_days <= 30    ~ "Stale",
    TRUE              ~ "Very stale"
  )
}

pt_age_label <- function(age_days) {
  dplyr::case_when(
    is.na(age_days) ~ "Not available",
    age_days == 0   ~ "today",
    age_days == 1   ~ "1 day old",
    TRUE            ~ paste0(age_days, " days old")
  )
}

pt_depth_table_html <- function(depths, values, dates, ages, sensors, sensor_counts) {
  if (length(depths) == 0 || all(is.na(depths))) {
    return("<span style='color:#666;'>No recent soil-moisture values found.</span>")
  }

  ord <- order(match(depths, standard_depth_order_in), depths, na.last = TRUE)
  depths <- depths[ord]
  values <- values[ord]
  dates <- dates[ord]
  ages <- ages[ord]
  sensors <- sensors[ord]
  sensor_counts <- sensor_counts[ord]

  rows <- purrr::pmap_chr(
    list(depths, values, dates, ages, sensors, sensor_counts),
    function(depth, value, date, age, sensor, sensor_count) {
      sensor_note <- ""
      if (!is.na(sensor_count) && sensor_count > 1) {
        sensor_note <- paste0(" <span style='color:#666;'>(avg of ", sensor_count, " sensors)</span>")
      }

      paste0(
        "<tr>",
        "<td style='padding:1px 6px 1px 0; text-align:right;'>", depth, "&quot;</td>",
        "<td style='padding:1px 6px;'>", ifelse(is.na(value), "NA", paste0(pt_fmt_num(value, 1), "%")), sensor_note, "</td>",
        "<td style='padding:1px 0; color:#555;'>", ifelse(is.na(date), "NA", as.character(date)), "</td>",
        "<td style='padding:1px 0 1px 6px; color:#555;'>", pt_age_label(age), "</td>",
        "</tr>"
      )
    }
  )

  paste0(
    "<table style='border-collapse:collapse; font-size:12px;'>",
    "<tr><th style='text-align:right; padding-right:6px;'>Depth</th>",
    "<th style='text-align:left; padding-right:6px;'>Latest</th>",
    "<th style='text-align:left;'>Date</th>",
    "<th style='text-align:left; padding-left:6px;'>Age</th></tr>",
    paste(rows, collapse = ""),
    "</table>"
  )
}

pt_make_popup_html <- function(row) {
  depth_label <- ifelse(is.na(row$display_depth_in), "Not available", paste0(row$display_depth_in, "&quot;"))
  value_label <- ifelse(is.na(row$display_sms_pct), "Not available", paste0(pt_fmt_num(row$display_sms_pct, 1), "%"))

  link_html <- ""
  if (!is.na(row$site_page_url) && nzchar(row$site_page_url)) {
    link_html <- paste0(
      "<br><a href='", row$site_page_url, "' target='_blank' rel='noopener noreferrer'>Open NRCS station page</a>"
    )
  }

  paste0(
    "<b>", row$station_name, "</b><br>",
    "<b>Type:</b> SCAN<br>",
    "<b>Provider:</b> USDA NRCS NWCC<br>",
    "<b>Station ID:</b> ", row$site_code, "<br>",
    "<b>Elevation:</b> ", ifelse(is.na(row$elevation_ft), "Not available", paste0(formatC(row$elevation_ft, format = "f", digits = 0, big.mark = ","), " ft")), "<br>",
    "<b>Location:</b> ", ifelse(is.na(row$county), "", paste0(row$county, ", ")), row$state, "<br>",
    "<b>Lat/Lon:</b> ", sprintf("%.6f, %.6f", row$latitude, row$longitude), "<br>",
    "<hr style='margin:4px 0;'/>",
    "<b>Latest soil moisture:</b> ", value_label, " at ", depth_label, "<br>",
    "<b>Observation date:</b> ", ifelse(is.na(row$display_obs_date), "Not available", row$display_obs_date), "<br>",
    "<b>Observation age:</b> ", pt_age_label(row$display_obs_age_days), "<br>",
    "<b>Status:</b> ", row$display_status_label, "<br>",
    "<b>Available depths:</b> ", ifelse(is.na(row$available_depths_in), "Not available", row$available_depths_in), "<br>",
    "<div style='margin-top:4px;'><b>Depth detail:</b><br>", row$depth_table_html, "</div>",
    "<div style='font-size:11px; color:#555; margin-top:4px;'>Historical percentiles and ribbon plots will be added after the local SCAN history summary is built.</div>",
    link_html
  )
}

pt_make_feature <- function(row) {
  props <- as.list(row[setdiff(names(row), c("longitude", "latitude"))])

  ## jsonlite writes data-frame row values as length-one vectors. Convert simple
  ## values to scalars while leaving NA values as JSON null.
  props <- lapply(props, function(v) {
    if (length(v) == 0) return(NULL)
    if (length(v) == 1 && is.na(v)) return(NULL)
    if (length(v) == 1) return(v[[1]])
    v
  })

  list(
    type = "Feature",
    geometry = list(
      type = "Point",
      coordinates = list(as.numeric(row$longitude), as.numeric(row$latitude))
    ),
    properties = props
  )
}

# ---- 4. Read station index --------------------------------------------------

if (!file.exists(station_index_csv)) {
  stop("Missing SCAN station-index CSV: ", station_index_csv)
}

station_index <- readr::read_csv(station_index_csv, show_col_types = FALSE)

required_cols <- c(
  "station_uid", "station_name", "site_code", "state", "county",
  "elevation_ft", "latitude", "longitude", "site_page_url"
)
missing_cols <- setdiff(required_cols, names(station_index))
if (length(missing_cols) > 0) {
  stop("SCAN station index is missing required field(s): ", paste(missing_cols, collapse = ", "))
}

station_index <- station_index |>
  mutate(
    station_uid = pt_chr(station_uid),
    station_name = pt_chr(station_name),
    site_code = suppressWarnings(as.integer(site_code)),
    state = pt_chr(state),
    county = pt_chr(county),
    elevation_ft = pt_num(elevation_ft),
    latitude = pt_num(latitude),
    longitude = pt_num(longitude),
    site_page_url = pt_chr(site_page_url),
    data_page_url = if ("data_page_url" %in% names(station_index)) pt_chr(data_page_url) else NA_character_,
    source_url = if ("source_url" %in% names(station_index)) pt_chr(source_url) else NA_character_,
    start_year = if ("start_year" %in% names(station_index)) suppressWarnings(as.integer(start_year)) else NA_integer_,
    status = if ("status" %in% names(station_index)) pt_chr(status) else NA_character_
  ) |>
  filter(!is.na(site_code), !is.na(latitude), !is.na(longitude)) |>
  distinct(site_code, .keep_all = TRUE)

message("SCAN stations in index: ", nrow(station_index))
message("Lookback days: ", lookback_days)
message("Fetch years: ", paste(fetch_years, collapse = ", "))

# ---- 5. Fetch recent soil-moisture data ------------------------------------

fetch_one_scan_year <- function(site_code, year) {
  message("Fetching SCAN SMS site ", site_code, ", year ", year, "...")

  out <- tryCatch(
    {
      x <- soilDB::fetchSCAN(
        site.code = site_code,
        year = year,
        report = "SMS",
        timeseries = "Daily",
        tz = "UTC"
      )

      if (!is.list(x) || !"SMS" %in% names(x) || is.null(x$SMS) || nrow(x$SMS) == 0) {
        return(tibble())
      }

      tibble::as_tibble(x$SMS)
    },
    error = function(e) {
      warning("SCAN SMS fetch failed for site ", site_code, ", year ", year, ": ", conditionMessage(e))
      tibble()
    }
  )

  if (request_pause_sec > 0) Sys.sleep(request_pause_sec)
  out
}

fetch_grid <- tidyr::expand_grid(
  site_code = station_index$site_code,
  year = fetch_years
)

sms_raw <- purrr::pmap_dfr(
  fetch_grid,
  function(site_code, year) {
    fetch_one_scan_year(site_code, year)
  }
)

if (nrow(sms_raw) == 0) {
  warning("No SCAN SMS rows were returned. Publishing station features with missing latest values.")

  depth_latest <- tibble(
    site_code = integer(),
    depth_in = integer(),
    sms_pct = numeric(),
    obs_date = as.Date(character()),
    obs_datetime_utc = character(),
    sensor_id = character(),
    sensor_count = integer(),
    obs_age_days = integer()
  )

} else {

  sms_clean <- sms_raw |>
    mutate(
      site_code = suppressWarnings(as.integer(Site)),
      obs_date = as.Date(Date),
      obs_datetime_utc = if ("datetime" %in% names(sms_raw)) {
        format(lubridate::with_tz(as.POSIXct(datetime, tz = "UTC"), "UTC"), "%Y-%m-%dT%H:%M:%SZ")
      } else {
        NA_character_
      },
      sms_pct = suppressWarnings(as.numeric(value)),
      depth_in = pt_depth_in_from_sensor(sensor.id, depth),
      sensor_id = as.character(sensor.id)
    ) |>
    filter(
      !is.na(site_code),
      !is.na(depth_in),
      !is.na(obs_date),
      obs_date >= lookback_start_date,
      obs_date <= feed_build_date_utc,
      !is.na(sms_pct)
    )

  ## Latest by station/depth. If multiple sensors at the same station/depth
  ## report on the latest date, average them and preserve the sensor IDs/count
  ## so the popup can disclose that an averaged value was used.
  depth_latest <- sms_clean |>
    group_by(site_code, depth_in) |>
    filter(obs_date == max(obs_date, na.rm = TRUE)) |>
    summarise(
      sms_pct = mean(sms_pct, na.rm = TRUE),
      obs_date = max(obs_date, na.rm = TRUE),
      obs_datetime_utc = {
        z <- na.omit(obs_datetime_utc)
        if (length(z) == 0) NA_character_ else z[1]
      },
      sensor_id = paste(sort(unique(sensor_id)), collapse = ", "),
      sensor_count = dplyr::n_distinct(sensor_id),
      .groups = "drop"
    ) |>
    mutate(
      obs_age_days = as.integer(feed_build_date_utc - obs_date)
    )
}

# ---- 6. Build feature properties -------------------------------------------

station_depth_summary <- depth_latest |>
  group_by(site_code) |>
  summarise(
    available_depths_in = paste(sort(unique(depth_in), na.last = NA), collapse = ", "),
    depth_values_json = jsonlite::toJSON(
      purrr::pmap(
        list(depth_in, sms_pct, obs_date, obs_age_days, sensor_id, sensor_count),
        function(depth_in, sms_pct, obs_date, obs_age_days, sensor_id, sensor_count) {
          list(
            depth_in = depth_in,
            sms_pct = round(sms_pct, 2),
            obs_date = as.character(obs_date),
            obs_age_days = obs_age_days,
            sensor_id = sensor_id,
            sensor_count = sensor_count
          )
        }
      ),
      auto_unbox = TRUE
    ),
    depth_table_html = pt_depth_table_html(depth_in, sms_pct, obs_date, obs_age_days, sensor_id, sensor_count),
    .groups = "drop"
  )

select_display_depth <- function(depths) {
  depths <- as.integer(depths)
  depths <- depths[!is.na(depths)]
  if (length(depths) == 0) return(NA_integer_)

  pref <- display_depth_preference_in[display_depth_preference_in %in% depths]
  if (length(pref) > 0) return(pref[1])

  depths[order(match(depths, standard_depth_order_in), depths, na.last = TRUE)][1]
}

display_latest <- depth_latest |>
  group_by(site_code) |>
  mutate(display_depth_in_tmp = select_display_depth(depth_in)) |>
  filter(depth_in == dplyr::first(display_depth_in_tmp)) |>
  slice(1) |>
  ungroup() |>
  transmute(
    site_code,
    display_depth_in = depth_in,
    display_sms_pct = round(sms_pct, 2),
    display_obs_date = as.character(obs_date),
    display_obs_datetime_utc = obs_datetime_utc,
    display_obs_age_days = obs_age_days,
    display_sensor_id = sensor_id,
    display_sensor_count = sensor_count,
    display_status_class = pt_stale_class(obs_age_days),
    display_status_label = pt_stale_label(obs_age_days)
  )

features_df <- station_index |>
  left_join(station_depth_summary, by = "site_code") |>
  left_join(display_latest, by = "site_code") |>
  mutate(
    feed_build_time_utc = feed_build_time_utc,
    lookback_days = lookback_days,
    available_depths_in = na_if(available_depths_in, ""),
    depth_values_json = ifelse(is.na(depth_values_json), "[]", depth_values_json),
    depth_table_html = ifelse(
      is.na(depth_table_html),
      "<span style='color:#666;'>No recent soil-moisture values found.</span>",
      depth_table_html
    ),
    display_status_class = ifelse(is.na(display_status_class), "missing", display_status_class),
    display_status_label = ifelse(is.na(display_status_label), "No recent observation", display_status_label),
    hover_text = paste0(
      station_name,
      "\nSCAN soil moisture",
      "\nDisplay depth: ", ifelse(is.na(display_depth_in), "NA", paste0(display_depth_in, " in")),
      "\nLatest: ", ifelse(is.na(display_sms_pct), "NA", paste0(pt_fmt_num(display_sms_pct, 1), "%")),
      "\nAge: ", pt_age_label(display_obs_age_days)
    )
  )

features_df$popup_html <- purrr::pmap_chr(features_df, function(...) {
  row <- tibble::as_tibble(list(...))
  pt_make_popup_html(row[1, ])
})

# ---- 7. Write GeoJSON and summary ------------------------------------------

if (!dir.exists(dirname(out_geojson))) dir.create(dirname(out_geojson), recursive = TRUE, showWarnings = FALSE)
if (!dir.exists(dirname(out_summary))) dir.create(dirname(out_summary), recursive = TRUE, showWarnings = FALSE)

features <- purrr::pmap(
  features_df,
  function(...) {
    row <- tibble::as_tibble(list(...))
    pt_make_feature(row[1, ])
  }
)

geojson <- list(
  type = "FeatureCollection",
  name = "BRIM SCAN soil moisture latest",
  feed_build_time_utc = feed_build_time_utc,
  features = features
)

jsonlite::write_json(
  geojson,
  path = out_geojson,
  auto_unbox = TRUE,
  pretty = TRUE,
  na = "null"
)

summary_tbl <- tibble::tibble(
  metric = c(
    "feed_build_time_utc",
    "station_index_rows",
    "features_written",
    "stations_with_any_recent_sms",
    "stations_without_recent_sms",
    "depth_rows_latest",
    "lookback_days",
    "lookback_start_date",
    "fetch_years",
    "display_depth_preference_in"
  ),
  value = c(
    feed_build_time_utc,
    as.character(nrow(station_index)),
    as.character(nrow(features_df)),
    as.character(sum(!is.na(features_df$available_depths_in))),
    as.character(sum(is.na(features_df$available_depths_in))),
    as.character(nrow(depth_latest)),
    as.character(lookback_days),
    as.character(lookback_start_date),
    paste(fetch_years, collapse = ", "),
    paste(display_depth_preference_in, collapse = ", ")
  )
)

summary_obj <- list(
  feed_build_time_utc = feed_build_time_utc,
  station_index_rows = nrow(station_index),
  features_written = nrow(features_df),
  stations_with_any_recent_sms = sum(!is.na(features_df$available_depths_in)),
  stations_without_recent_sms = sum(is.na(features_df$available_depths_in)),
  depth_rows_latest = nrow(depth_latest),
  lookback_days = lookback_days,
  lookback_start_date = as.character(lookback_start_date),
  fetch_years = fetch_years,
  display_depth_preference_in = display_depth_preference_in,
  status_counts = as.list(table(features_df$display_status_class, useNA = "ifany")),
  depth_counts = as.list(table(depth_latest$depth_in, useNA = "ifany"))
)

jsonlite::write_json(
  summary_obj,
  path = out_summary,
  auto_unbox = TRUE,
  pretty = TRUE,
  na = "null"
)

message("Wrote SCAN soil-moisture latest GeoJSON: ", out_geojson)
message("Wrote SCAN soil-moisture latest summary: ", out_summary)
message("\nSCAN latest-feed summary:")
print(summary_tbl, n = Inf)
